### ISSUE TITLE
how to use

### ISSUE THREAD

**Issue by caizhe666** [FloatingPoint-MC/NeteaseCheatPlus#1]

**Comment by vlouboos** [comment]
I'm going to create a maven file so that you can import it automatically

**Comment by ll11l1lIllIl1lll** [comment]
> I'm going to create a maven file so that you can import it automatically

why not use gradle?

**Comment by vlouboos** [comment]
> 

Because I don't know how to write gradle file.

**Comment by vlouboos** [comment]
It's been updated
